### ISSUE TITLE
Bug in the function _calculateLux(uint16_t _lightBits)

### ISSUE THREAD

**Issue by ghost** [sparkfun/SparkFun_Ambient_Light_Sensor_Arduino_Library#1]
Hello, today we have the following code in line 425 at the url 
[(https://github.com/sparkfun/SparkFun_Ambient_Light_Sensor_Arduino_Library/blob/master/src/SparkFun_VEML6030_Ambient_Light_Sensor.cpp)]

`
uint32_t SparkFun_Ambient_Light::_calculateLux(uint16_t _lightBits){

  float _luxConv; 
  uint8_t _convPos;  

  float _gain = readGain(); 
  uint16_t _integTime = readIntegTime();

  // Here the gain is checked to get the position of the conversion value
  // within the integration time arrays. These values also represent the bit
  // values for setting the gain. 
  if (_gain == 2.00) 
    _convPos = 0;
  else if (_gain == 1.00)
    _convPos = 1; 
  else if (_gain == .125)
    _convPos = 2; 
  else if (_gain == .25)
    _convPos = 3; 
  else
    return UNKNOWN_ERROR;

`
But if we follow the table resolution (Lux/bit) of the hookup guide of the VEML6030 here [(https://learn.sparkfun.com/tutorials/qwiic-ambient-light-sensor-veml6030-hookup-guide?_ga=2.68808725.549100198.1574927000-1168471852.1567063892)], the gain==.125 should be reverse with the gain==.25 .

So we should have a code like this
`
uint32_t SparkFun_Ambient_Light::_calculateLux(uint16_t _lightBits){

  float _luxConv; 
  uint8_t _convPos;  

  float _gain = readGain(); 
  uint16_t _integTime = readIntegTime();

  // Here the gain is checked to get the position of the conversion value
  // within the integration time arrays. These values also represent the bit
  // values for setting the gain. 
  if (_gain == 2.00) 
    _convPos = 0;
  else if (_gain == 1.00)
    _convPos = 1; 
  else if (_gain == .25)
    _convPos = 2; 
  else if (_gain == .125)
    _convPos = 3; 
  else
    return UNKNOWN_ERROR;

`
Tell me if I'm correct.
Thanks.

**Comment by edspark** [comment]
Yep you are correct. 

Fix here: https://github.com/sparkfun/SparkFun_Ambient_Light_Sensor_Arduino_Library/commit/8932a9bb542e3c8a3a653969ef62e994f41c687a

**Comment by edspark** [comment]
Thank you for digging into the code and finding the bug.
