### ISSUE TITLE
What is the difference between the function readLight() and readWhiteLigth() ?

### ISSUE THREAD

**Issue by ghost** [sparkfun/SparkFun_Ambient_Light_Sensor_Arduino_Library#2]
What is the difference between the function readLight() and readWhiteLigth() ?

The functions are in https://github.com/sparkfun/SparkFun_Ambient_Light_Sensor_Arduino_Library/blob/master/src/SparkFun_VEML6030_Ambient_Light_Sensor.cpp

readLight() in line 373 and readWhiteLigth() in line 391.

Thanks .

**Comment by edspark** [comment]
I'm not entirely learned on how this applies in real world applications but according to the datasheet, the white light channel offers "_higher responsivity for a much wider wavelength spectrum_"... and there are a number of graphs to support their evidence if you check the datasheet [here](https://github.com/sparkfun/SparkFun_Ambient_Sensor_VEML6030/blob/master/Documentation/ApplicationNoteVEML6030.pdf) in pages 12-14 .🤔 My limited understanding is that using the `readWhiteLight()` is better if you know that your light source has a strong Infrared component - again from the datasheet. If you test this in any way or gain some understanding, I'd love to hear it! 👍
