### ISSUE TITLE
arduino due+VEML6030 always give us Lux=0

### ISSUE THREAD

**Issue by ghost** [sparkfun/SparkFun_Ambient_Light_Sensor_Arduino_Library#3]
Hello I'm using an arduino due and a sparkfun ambient ligth VEML6030 https://www.sparkfun.com/products/15436. My Due board is 1.6.12, my IDE arduino is 1.8.12.

The pins SDA and SCL of the VEML6030 are on the SDA20 and SCL21 of the arduino due.
The pin 3V3 is on the 3.3V of the arduino due.
The pin GND is on the GND of the arduino due.

The code used is the following
`
#include <Wire.h>
#include <SparkFun_VEML6030_Ambient_Light_Sensor.h>

#define AL_ADDR 0x48

SparkFun_Ambient_Light light(AL_ADDR);

// Possible integration times in milliseconds: 800, 400, 200, 100, 50, 25
// Higher times give higher resolutions and should be used in darker light. 

long luxVal = 0;

void setup()
{

  Wire.begin();
  Serial.begin(115200);

  if(light.begin())
    Serial.println("Ready to sense some light!"); 
  else
    Serial.println("Could not communicate with the sensor!");

  // Again the gain and integration times determine the resolution of the lux
  // value, and give different ranges of possible light readings. Check out
  // hoookup guide for more info. 
  light.setGain(0.125);
  light.setIntegTime(100);

  Serial.println("Reading settings..."); 
  Serial.print("Gain: ");
  float gainVal = light.readGain();
  Serial.print(gainVal, 3); 
  Serial.print(" Integration Time: ");
  int timeVal = light.readIntegTime();
  Serial.println(timeVal);

}

void loop()
{

  luxVal = light.readLight();
  Serial.print("Ambient Light Reading: ");
  Serial.print(luxVal);
  Serial.println(" Lux");  
  delay(1000);

}
`

The code is from [https://learn.sparkfun.com/tutorials/qwiic-ambient-light-sensor-veml6030-hookup-guide?_ga=2.229015452.1016202851.1584717447-1168471852.1567063892](url) part 1 ambient ligth basics.

The results are the following :
Ready to sense some light!
Reading settings...
Gain: 1.000 Integration Time: 100
Ambient Light Reading: 0 Lux
Ambient Light Reading: 0 Lux
Ambient Light Reading: 0 Lux
Ambient Light Reading: 0 Lux
Ambient Light Reading: 0 Lux
Ambient Light Reading: 0 Lux

The gain=1 and integration time=100 is linked with the frames of 0.

My issue is, why I have always ambient light reading equal to 0 ?

Thanks in advance.

**Comment by edspark** [comment]
Hello! These types of questions are best directed at the [forums](https://forum.sparkfun.com). Please return if you find something is incorrect with the library. Thanks!
